### ISSUE TITLE
Aborted(`Module.asm` has been replaced by `wasmExports` (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name))

### ISSUE THREAD

**Issue by samsieber** [ajrcarey/pdfium-render#134] opened 2024-01-25 15:08 UTC
This is much like #128; it appears the wasmTable lookup was missed.

```
Aborted(`Module.asm` has been replaced by `wasmExports` (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name))

pdfium-render::initialize_pdfium_render(): Unable to locate wasmTable```
```
I hacked up the pdfium-lib wasm's js file to be able to load as an ESM module (kinda - I got it working with Vite through some manual modification), and I'm running it a webworker, so I can't even manually patch the window object (since in a web worker the window object doesn't exist).

I have a commit here: https://github.com/samsieber/pdfium-render/commit/0846f61eb7675285144ae0886743ad79feb0447a; I'd be happy to submit it as a PR if you'd like. I've just noticed you have what seems to be a pretty set pattern of issue, then commit referencing issue.

**Comment by ajrcarey** [comment] 2024-01-27 18:46
Hi @samsieber , thank you for reporting the issue.

I cannot reproduce the issue using `pdfium-render` 0.8.17 and `pdfium-lib` release 6183 downloaded from https://github.com/paulocoutinhox/pdfium-lib/releases/tag/6183.

Please confirm the version of `pdfium-lib` you are using, and walk me through the exact steps required to reproduce the problem.

**Comment by ajrcarey** [comment] 2024-02-04 18:52
As there have been no further comments and I am unable to reproduce the problem, I am closing the issue. Please provide the steps required to reproduce the problem before re-opening the issue.

**Comment by samsieber** [comment] 2024-02-05 20:18
Sorry for the long delay getting back to you; I was out last week.

I've set up a minimal reproduction here: https://github.com/samsieber/pdfium-render-128-repro . If you have yarn and wasm-pack installed globally, you should be able to clone it, go in and run `yarn && yarn wasm && yarn dev` to build and run the example. It'll pop up the following screen:

![Screenshot 2024-02-05 at 2 15 27 PM](https://github.com/ajrcarey/pdfium-render/assets/5694469/9b4aff9d-ca9d-437e-acc5-ef2e89fe14db)

I'm using a bundler, so manually tweaked the pdfium.js file to work with ESM loading, and renamed the wasm file from pdfium.wasm to pdfium_bg.wasm. See this change: https://github.com/samsieber/pdfium-render-128-repro/commit/ff5ed61a8af5267bd68a203d4cc9ea5c99687829#diff-97547cdd138a3638f89f726f3a7609dbeca961cf9ac13255a1392f56a0b21fd9 for the exact changes I made. It basically just changed how I imported it, how I fed it the url of the wasm asset, and the name of the wasm asset (to work with my particular wasm loader).

That said, I'd been fine working around it with this nice line `window.wasmTable = pdfiumModule.wasmExports.__indirect_function_table;`, but I'm now loading it in a webworker, where the window fallback doesn't work (because window is undefined there).

**Comment by samsieber** [comment] 2024-02-05 20:20
I've added the reproduction, let me know if you have questions. I'm not sure if you'll see this since it's closed, and I'm not sure how to reopen it, so I'll ping you here @ajrcarey. Also, thanks for maintaining this.

**Comment by ajrcarey** [comment] 2024-02-09 16:44
Thank you for the reproduction steps and repo @samsieber , that's very useful. I agree with you that the problem is likely due to the packaging mechanism; I'm not a web developer so I'm reluctant to get too deep into that. I have made a small change which (I _think_) addresses the issue in your sample repo, and I have confirmed it doesn't break anything when following the build instructions at https://github.com/ajrcarey/pdfium-render/blob/master/examples/README.md. You can test it by taking `pdfium-render` as a source dependency in your Cargo.toml file.

**Comment by ajrcarey** [comment] 2024-02-16 19:16
As there have been no further comments, and I believe the issue is resolved, I will shortly close the issue. Allowing another three days for feedback from @samsieber .

**Comment by samsieber** [comment] 2024-02-19 23:01
This does address the issue. Thanks for your help!

**Comment by ajrcarey** [comment] 2024-02-21 21:57
Updated README. Ready to release as part of version 0.8.18.

**Closed by ajrcarey** 2024-02-21 21:57 UTC
