### ISSUE TITLE
sync crate feature is unsafe to use with OnceCell

### ISSUE THREAD

**Issue by bavardage** [ajrcarey/pdfium-render#106] opened 2023-08-30 16:54 UTC
demonstrated/described in https://github.com/ajrcarey/pdfium-render/pull/105

**Comment by ajrcarey** [comment] 2023-09-02 15:27
Comments @bavardage submitted as part of PR #105, reproduced here verbatim:



I've been running into something similar in my usage of pdfium-render, and have attempted to reproduce via modifying the thread_safe example.

The readme alludes to it being ok, when using the sync feature, to initialize pdfium using something like a once_cell (I may have understood this part).

From reading the code though I don't see then how this would be protected - since the thread_safe feature seems to protect at bindings init time, but if you init once and then share around via sync feature there's nothing stopping concurrent access.

With this modified example I seem to reliably get segfaults when running this locally with
cargo run --example thread_safe --features="thread_safe,sync"

In my actual usecase (where I'm using some other features of pdfium, but seem to reliably hit with text extraction) I see a mixture of problems:

    text extraction is incorrect - missing characters/garbled output
    format errors when loading valid documents
    unknown pdfium errors (PdfiumLibraryInternalError)
    ../base/allocator/partition_allocator/partition_page.h(633) Check failed: entry != freelist_head

**Comment by ajrcarey** [comment] 2023-09-02 15:28
Hi @bavardage , thank you for reporting the problem. If the documentation is misleading in any way, let's fix that; but other than making it abundantly clear that multi-threading with Pdfium is inherently unsafe and entirely at your own risk, I'm not sure what else I can do here. I looked at your PR but it did not (as far I could see) provide any remedy, so I've closed it without action.

**Comment by ajrcarey** [comment] 2023-09-09 16:15
Updated README to emphasise `sync` is not thread-safe. Will be included in release 0.8.9.

**Closed by ajrcarey** 2023-09-09 16:15 UTC
