### ISSUE TITLE
[Windows] error LNK2019: unresolved external symbol FPDFPage_TransformAnnots

### ISSUE THREAD

**Issue by kernoeb** [ajrcarey/pdfium-render#173] opened 2024-11-18 15:47 UTC
Hi !

Since a new version of pdfium or pdfium_render, I can't build statically for Windows anymore :

```
error LNK2019: unresolved external symbol FPDFPage_TransformAnnots referenced in function _ZN129_$LT$pdfium_render..bindings..static_bindings..StaticPdfiumBindings$u20$as$u20$pdfium_render..bindings..PdfiumLibraryBindings$GT$24FPDFPage_TransformAnnots17h3900b3ef53e65f00E␍
          D:\a\pdf-reader\pdf-reader\target\x86_64-pc-windows-msvc\release\deps\pdfium_render-05792a1113cec5b8.dll : fatal error LNK1120: 1 unresolved externals␍
```

for context : 

- it's properly working on Linux and macOS
- i'm using pdfium 6721 with last version of pdfium_render (i also tried the last main/git version)

Based on issues, it seems that you're still working on bindings, but why does it work with Linux and macOS then ? 🤔 

Thank you !

**Comment by ajrcarey** [comment] 2024-11-18 20:43
Hi @kernoeb , thank you for reporting the issue. I have no problem statically linking to a dynamic build of Pdfium downloaded from https://github.com/bblanchon/pdfium-binaries/releases on Windows 11 using the following `Cargo.toml` and `main.rs` files:

```
[package]
name = "pdfium-issue-173"
version = "0.1.0"
edition = "2021"

[dependencies]
pdfium-render = { path = "../pdfium-render", features = ["static"] }
```

```
use pdfium_render::prelude::*;	

fn main() -> Result<(), PdfiumError> {
    let pdfium = Pdfium::new(Pdfium::bind_to_statically_linked_library()?);

    let document = pdfium.load_pdf_from_file("../pdfium-render/test/form-test.pdf", None)?;

    <rest of file as per https://github.com/ajrcarey/pdfium-render/blob/master/examples/annotations.rs>
```

Please provide your `Cargo.toml`, a minimal code sample that reproduces the problem, and the commands you are using to execute your build.

It's true I am working on the bindings, but only on the doc comments; the bindings themselves are stable. The binding for `FPDFPage_TransformAnnots` was added six months ago and has not changed since.

>  why does it work with Linux and macOS then ? 🤔

My instinct is that it's a difference in your environment configuration.

**Comment by kernoeb** [comment] 2024-11-18 21:05
In my case, i only upgraded `pdfium` to a new version, with the same method as before (it was working at the start of the year, that's what I'm thinking something changed, maybe in the way pdfium needs to be build ?).

I always built manually a `pdfium.lib` for Windows, and a `libpdfium.a` for macOS and Linux with this configuration : 

```
use_goma = false
treat_warnings_as_errors = false
clang_use_chrome_plugins = false
is_component_build = false
pdf_enable_v8 = false
pdf_is_standalone = true
pdf_is_complete_lib = true
pdf_enable_xfa = false
pdf_use_partition_alloc = false
use_sysroot = false
clang_use_chrome_plugins = false
use_custom_libcxx = false
is_debug = false
target_cpu = "x64"
target_os = "linux"
symbol_level = 0
```

then, the only thing to change is the `target_os` variable

<img width="200" alt="image" src="https://github.com/user-attachments/assets/927a9ecf-cdbe-47a3-8e8f-e0996a8e7395">

I tried the same configuration with a dynamic link (no pdf_is_complete_lib), and it works, it only happens when using the static build for some reason.

---

My `build.rs` looks like this : 

```rs
#[cfg(target_os = "macos")]
let path = Path::new("./resources/macos");

#[cfg(target_os = "linux")]
let path = Path::new("./resources/linux");

#[cfg(target_os = "windows")]
let path = Path::new("./resources/windows");

println!("cargo:rustc-link-lib=static=pdfium");
println!("cargo:rustc-link-search=native={}", path.display());

#[cfg(target_os = "macos")]
println!("cargo:rustc-link-lib=framework=CoreGraphics");

#[cfg(target_os = "macos")]
println!("cargo:rustc-link-lib=dylib=c++");
```

And my `cargo.toml` : 

```
[target.'cfg(target_os = "macos")'.dependencies]
pdfium-render = { version = "0.8.26", features = [ "static", "libc++", "thread_safe" ] }

[target.'cfg(target_os = "linux")'.dependencies]
pdfium-render = { version = "0.8.26", features = [ "static", "libc++", "thread_safe" ] }

[target.'cfg(target_os = "windows")'.dependencies]
pdfium-render = { version = "0.8.26", features = ["static", "thread_safe"] }
```

---

However, I didn't know I could use the prebuilt from `pdfium-binaries` to make a static build though, does it work for Linux and macOS ? I can't use `lib/libpdfium.dylib`, right ?

**Comment by Tebarem** [comment] 2024-11-20 01:36
Hey Im also looking into this. I cant figure out the wasm stuff at all specially with cloudflare/workers-rs . I was suggested to use the static feature flag and im getting 

```
46  | pub struct Pdfium {
    | ----------------- function or associated item `bind_to_statically_linked_library` not found for this struct
...
442 |         Pdfium::new(Pdfium::bind_to_statically_linked_library().unwrap())
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `Pdfium`
    ```

**Comment by ajrcarey** [comment] 2024-11-23 19:52
> does it work for Linux and macOS

It certainly works on Linux. I don't have a mac here to test it on, but it should work similarly.

> I cant figure out the wasm stuff at all specially with cloudflare/workers-rs

I'm confused by this. How is this related to this issue? Please explain clearly how your original issue is related to WASM; I don't see how it possibly can be, given you are trying to statically link to an external object library! If this is not related to this issue, please open a new issue, after carefully considering whether you are reporting a bug in `pdfium-render` or not. Issues that do not clearly identify a bug in `pdfium-render` are likely to be closed without comment.

>  was suggested to use the static feature flag

Where in the documentation does it suggest to use the static crate feature when compiling to WASM? Did you clearly follow and understand the WASM example in the repo? How were you intending to deploy a separate Pdfium WASM module as part of a Cloudflare worker?

**Comment by ajrcarey** [comment] 2024-11-23 19:53
> I tried the same configuration with a dynamic link (no pdf_is_complete_lib), and it works, it only happens when using the static build for some reason.

I will attempt to reproduce your problem on Windows later on this weekend.

**Comment by kernoeb** [comment] 2024-11-23 20:10
So basically, if for example, I use the `pdfium-mac-univ.tgz` file from pdfium-binaries, get the `.dylib` and put it in my `./resources/macos` directory, it should work ? If I do this, it tries to get the dylib dynamically when running the binary (in my case, i generate a `.node` with napi). 

If I generate a `libpdfium.a` instead, manually, it works properly (on Linux too).

But for some reason, I can't make it work on Windows now, but it still works when using an old version (i tried on a local windows and on an automatic github CI)

**Comment by ajrcarey** [comment] 2024-11-23 23:42
> I use the pdfium-mac-univ.tgz file from pdfium-binaries, get the .dylib and put it in my ./resources/macos directory, it should work?

Well, I would expect it to depend on the configuration of your LD_LIBRARY_PATH and PDFIUM_DYNAMIC_LIB_PATH environment variables to make sure the Rust compiler and linker can find the correct .dylib. But basically, yes, I would expect it to be that simple.

> If I do this, it tries to get the dylib dynamically when running the binary (in my case, i generate a .node with napi), it's not compiled with it.

That's correct; your binary is linked to that specific library, which in theory should provide a minor boost to performance (since dynamic binding has a non-zero cost for calling each FPDF_* function). But because the library is not built into your executable, you do still need to ship it alongside your compiled Rust application.

**Comment by kernoeb** [comment] 2024-11-23 23:50
Okay, thanks 👍
Unfortunately, in my project context, I can't ship the library with my `.node`, I need to build it in the executable like I always did, with the `libpdfium.a` or `pdfium.lib`. Let me know if you manage to make a fully static binary with a fresh `pdfium.lib` on Windows. (and btw, thanks for your hard work on this repo!)

**Comment by ajrcarey** [comment] 2024-11-24 00:24
> I always built manually a pdfium.lib for Windows

Please provide the exact steps you use to build your pdfium.dll, including details on your compiler toolchain (Visual Studio?).

**Comment by kernoeb** [comment] 2024-11-24 00:33
Initially I did it manually following all steps from https://pdfium.googlesource.com/pdfium/ and https://chromium.googlesource.com/chromium/src/+/main/docs/windows_build_instructions.md

I also discovered recently this project too, which basically do the same steps easily : https://github.com/toeverything/pdfium-builder

I don't have access to my Windows machine build right now, but I remember installing all the requirements from the windows build instruction doc (Visual Studio 2022, etc). 

The steps are very similar between Linux, macOS and Windows. The lib file seems to be properly generated, no particular error (and it works with the generated dynamic version).

**Comment by ajrcarey** [comment] 2024-11-24 02:10
Ok. Thanks for pointing me at that `windows_build_instructions.md` document, that was very useful. It took a while to get everything installed and configured, but I was able to successfully build a static` pdfium.lib` using the following` args.gn` file:

```
treat_warnings_as_errors = false
clang_use_chrome_plugins = false
is_component_build = false
pdf_enable_v8 = false
pdf_is_standalone = true
pdf_is_complete_lib = true
pdf_enable_xfa = false
pdf_use_partition_alloc = false
pdf_use_skia = false
use_sysroot = false
use_custom_libcxx = false
is_debug = false
is_clang = true
# target_cpu = "x64" # Not sure if commenting these out...
# target_os = "linux" # ... actually makes a difference
symbol_level = 0
```

I was then able to copy this` pdfium.lib` file into a new directory, use the same `Cargo.toml` and main.rs files I mentioned above, statically link against my `pdfium.lib` by setting the `PDFIUM_STATIC_LIB_PATH` to the path of the folder containing `pdfium.lib`, and build a .exe file using `cargo build`.

The only problem I experienced was a linker problem. I had had to switch from the `stable-x64_64-pc-windows-gnu` toolchain to the `stable-x86_64-pc-windows-msvc toolchain`. Once I did that, linking completed without errors, a .exe file was produced, and I was able to run that .exe file with no problems. I copied the .exe to a different directory and was able to run it from that directory fine as well, without `pdfium.lib` being available.

There was no mention of `FPDFPage_TransformAnnots` at any point.

**Comment by ajrcarey** [comment] 2024-11-24 02:12
So my conclusion from all this is that there is a problem somewhere in your build environment. Can you check the following for me:

* Your toolchain as listed by `rustup toolchain list`
* Your current toolchain version
* Any differences in the `args.gn` settings file for Pdfium build
* The `PDFIUM_STATIC_LIB_PATH` setting you are using when you run `cargo build`, vs the actual location of your `pdfium.lib` file

**Comment by ajrcarey** [comment] 2024-11-24 02:13
Noted https://chromium.googlesource.com/chromium/src/+/main/docs/windows_build_instructions.md and toolchain requirements in #53.

**Comment by kernoeb** [comment] 2024-11-24 14:20
Ok, so I created a new from scratch Rust project from my Windows build machine and first got the same issue.

But I tried to set the environment variable in `.cargo/config.toml` instead with the absolute path, and got a different issue about non resolved external symbol / std.

Then, I used your `args.gn` (I think the `is_clang` part is important), and it works properly !

I don't understand why it worked before, I'm sure I succeed to make a build before with the relative path in the `build.rs`, but maybe there was a change on cargo or something, but whatever, now it works !

Thanks ! Your help was really helpful.

**Comment by ajrcarey** [comment] 2024-11-24 16:19
That's great news, glad you got it working and happy to help.

For your WASM problem, please open a separate issue (but please reviewe all the WASM-specific examples and documentation in the repo first). I'm going to close this issue now.

**Closed by ajrcarey** 2024-11-24 16:19 UTC
