### ISSUE TITLE
chrono  error

### ISSUE THREAD

**Issue by cyberdoors** [ajrcarey/pdfium-render#160] opened 2024-08-29 02:45 UTC
26 |     use chrono::{DateTime, Utc};
   |                            ^^^
   |                            |
   |                            no `Utc` in the root
   |                            help: a similar name exists in the module: `UTC`

error[E0432]: unresolved import `chrono::Utc`

cargo tree

chrono v0.3.0
└── pdfium-render v0.8.25 (https://github.com/ajrcarey/pdfium-render.git#376bc4ba) (*)

chrono v0.4.38
└── text_analysis v0.3.4

**Comment by ajrcarey** [comment] 2024-08-29 12:44
Hi @cyberdoors , thank you for reporting the issue.

`chrono v0.3.0` is seven years old at this point. Is there a reason you're locked to such an old version?

I think the simplest solution is to change the chrono dependency entry in Cargo.toml to `chrono = "0.4, <= 0.4.31"` to establish a minimum bound of 0.4.0.

**Comment by ajrcarey** [comment] 2024-08-29 17:36
It's odd because if I force a downgrade to `chrono 0.3.0`, `cargo update` with a `chrono` dependency of `"<= 0.4.31"` upgrades to 0.4.31 without complaint. But anyway, to avoid any possibility of failure, I suggest updating to `"0.4, <= 0.4.31"` as I mentioned above.

**Comment by ajrcarey** [comment] 2024-08-31 14:16
As there have been no further comments and I believe the issue is resolved, I will shortly close the issue. Feel free to reopen if you feel the issue has not been resolved.

Patched will be included in release of crate version 0.8.25.

**Closed by ajrcarey** 2024-08-31 14:16 UTC
