### ISSUE TITLE
form field values (checkbox, radio button) appear to be incorrect

### ISSUE THREAD

**Issue by bavardage** [ajrcarey/pdfium-render#97] opened 2023-07-24 22:19 UTC
pdfium-render % cargo run --example form_fields > example-output.txt

[example-output.txt](https://github.com/ajrcarey/pdfium-render/files/12152944/example-output.txt)

See for example 
`Page 0, annotation 4: Checkbox, Some("form1[0].#subform[0].CheckBox1[0]") has form field value: false`

but I'm pretty sure this should be true

More broadly, I've been unable to get anything other than `false` from a checkbox/radio button

This could well be a pdfium bug (vs pdfium render) but there does appear to be test cases in pdfium itself for e.g. `FPDFAnnot_IsChecked `

https://pdfium.googlesource.com/pdfium/+/refs/heads/main/fpdfsdk/fpdf_annot_embeddertest.cpp

I ran the example there (https://github.com/lukas-w/pdfium/blob/main/testing/resources/click_form.pdf) through pdfium-render and couldn't get anything other than false as output

**Comment by ajrcarey** [comment] 2023-07-30 17:31
Hi @bavardage , thank you for reporting the issue.

Let's focus on the `click_form.pdf` example, since it's more easily digestible than the `form-test.pdf` sample file included in the `pdfium-render` samples.

I _think_ what's happening here is that `click_form.pdf` is using appearance streams, not boolean values, to visually indicate to the viewer which items are selected. Flipping between the appearance streams makes a _visual_ change, but does not necessarily adjust the underlying boolean value that Pdfium appears to be looking for when calling the `FPDFAnnot_IsChecked()` function. (Indeed, reading the PDF reference, I don't see anything about storage of booleans for checkboxes or radio buttons anywhere, so I don't know what Pdfium's actually looking for here.) This explains why Pdfium (and therefore `pdfium-render`) constantly returns `false` as the underlying value: I believe that this is _technically_ correct - whatever boolean value Pdfium is looking for in `FPDFAnnot_IsChecked()` isn't being set - but it's hardly a useful, or expected, result when it flies in the face of what's presented visually.

The PDF Reference manual version 1.7 states that, for checkboxes, it's recommended to use the "Yes" appearance stream for a customised checked checkbox, and the "Off" appearance stream for a customised unchecked checkbox. And indeed this is exactly the case in `click_form.pdf`: when the second, non-read-only checkbox is clicked, its appearance stream setting changes from "Off" to "Yes". 

In the PDF file, the checkbox's `V` attribute stores which appearance stream is currently selected: "Off", or "Yes". This attribute can be retrieved from Pdfium using the `FPDFAnnot_GetFormFieldValue()` function. I've added the `.group_value()` function for both checkboxes and radio buttons, so you get the attribute value directly when working with `pdfium-render`.

For checkboxes, given there's a standard recommendation vis a vis "Off" and "Yes", I feel pretty comfortable about adjusting the `.is_checked()` function to check the currently set value directly. This has been done in the latest patch.

For radio buttons, the PDF standard's recommendation is for the `V` attribute _for each button in the control group_ to hold the appearance stream for whichever button is currently selected. For `click_form.pdf`, we can see that these values are "value1", "value", and "value3", and the currently set value for all radio buttons in the group does indeed change when clicked. However, "value1", "value", etc. are not standard terms in the way "Off" and "Yes" are for checkboxes, so I'm less comfortable testing for them directly in pdfium-render's `.is_checked()` function for radio buttons.

I'd like to experiment a little more with this to see if there's a reliable way to determine which appearance streams are assigned to which radio buttons.

You can take `pdfuim-render` as a git dependency in your Cargo.toml to expose the newly-added `.group_value()` function for checkboxes and radio buttons to play around with it yourself, and also verify that `.is_checked()` for checkboxes, at least, gives more expected results.

**Comment by bavardage** [comment] 2023-08-01 13:47
Really appreciate the explanation + your changes in https://github.com/ajrcarey/pdfium-render/commit/b77935eca4c31c90ef442d30d3d79d28681d8516 - the `.group_value()` function does exactly what I need

for radio buttons I agree the "value1" etc are not part of any standard. From poking around a bit/creating pdf forms, it seems for radio buttons you can assign each button a particular value.

**Comment by ajrcarey** [comment] 2023-09-10 18:12
Confirmed that retrieving the currently set appearance stream for a selected radio button matches the value set for the current group. This gives a good way, I think, of updating the `PdfFormRadioButtonField::is_checked()` function to correctly return an accurate result in situations where the underlying `FPDFAnnot_IsChecked()` Pdfium function returns `false`.

Added appearance stream and appearance mode retrieval support. Updated `PdfForm::field_values()` to correctly account for control groups. Updated documentation. Ready to release as part of crate version 0.8.11.

**Closed** 2023-09-11 01:28 UTC
